name: impulsa_reto_3_nadie_fuera
description: "Nadie Fuera — Banca Móvil Accesible"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: ^0.20.3
  meta: ^1.18.0

dev_dependencies:
  accessibility_tools: ^2.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
